language: python

python:
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - flake8
  - coverage run manage.py test && coverage report

after_success:
- coveralls
